### ISSUE TITLE
All link them option ? 

### ISSUE THREAD

**Issue by Slabhub** [usoonees/logseq-plugin-link-unlink#1]
not issues just req thnx

**Comment by usoonees** [comment]
Not easy to implement 😕.
Logseq does not provide the `getUnlinkedReferences` API so that we need to wait for the unlinked references to load at UI level

**Comment by CollCaz** [comment]
sorry if this is a dumb idea but wouldn't it be possible to have a link all button?
I'm not very familiar with javascript but wouldn't it be possible to add a link all button that runs the code associated with all the .link-button buttons?

Also thank you for the amazing plugin! I can't see myself using Logseq without it <3

**Comment by melat0nin** [comment]
> Not easy to implement 😕. Logseq does not provide the `getUnlinkedReferences` API so that we need to wait for the unlinked references to load at UI level

Is it possible to loop through all the detected unlinked references, and perform the linkage at that point? Very nice plugin btw, this should be core functionality imho

**Comment by usoonees** [comment]
Just add this button In the latest version, simply iterate through all the 'link' buttons and click on them :)
