### ISSUE TITLE
Feature request: Highlight page alias for linking

### ISSUE THREAD

**Issue by yiheinchai** [usoonees/logseq-plugin-link-unlink#10]
For example,

[[Dog]]
- alias:: dogs, animals

Current behaviour:
- When word is 'Dogs', 'Dog' is highlighted instead
- When word is 'animals', nothing is highlighted
    
Expected behaviour:
- When word is 'Dogs', 'Dogs' is highlighted
- When word is 'animals', 'animals' is highlighted

**Comment by usoonees** [comment]
Has the plugin been updated to the latest version? It should support aliases.

**Comment by usoonees** [comment]
Just updated a version, now it would highlight dogs first.
<img width="979" alt="image" src="https://user-images.githubusercontent.com/56818734/219876948-c2d63865-84ba-4142-be19-ad6d838acbed.png">

**Comment by yiheinchai** [comment]
thank you for the quick fix! appreciate it 🚀
