### ISSUE TITLE
Substrings of words considered keywords by the plugin

### ISSUE THREAD

**Issue by r6d2** [usoonees/logseq-plugin-link-unlink#11]
I've just noticed that the plugin seems to believe that #salud (a keyword for which I created a [[salud]] link) is the same as "saludo" or "saludó", and it suggests I link those to "salud".

Is this intended?

If it is, can it be made optional?

Or is there a workaround for this behavior?

Thanks in advance!

**Comment by usoonees** [comment]
Sorry for the late response, this is intended.

You can change the code in https://github.com/usoonees/logseq-plugin-link-unlink/blob/master/public/index.ts#L286
to `const reStr = "\\b(" + pageNames.join("|") + ")\\b";`

which only matches whole words in `pageNames`, and won't match "saludo" when  link "salud".
