### ISSUE TITLE
Suggestion: Unlink option

### ISSUE THREAD

**Issue by martin8032** [usoonees/logseq-plugin-link-unlink#5]
Linking unlinked terms is very helpful. But sometimes I need to do just the opposite: unlink a linked term. Could you add this functionality as well please?

**Comment by usoonees** [comment]
I have similar demand, but have to consider a better UI solution, cause most time we don't need this option 🤔

**Comment by usoonees** [comment]
I use this [wrap plugin](https://github.com/sethyuan/logseq-plugin-wrap) to do this.
![image](https://user-images.githubusercontent.com/56818734/212907968-e738aa99-5584-48b9-83e2-e61ca6706a4d.png)
