### ISSUE TITLE
Support for Alias 

### ISSUE THREAD

**Issue by Slabhub** [usoonees/logseq-plugin-link-unlink#9]
As you know that, Alias' have same thing for all page and tags in Logseq . 
Can you add function (maybe optional) for Alias ? 

For example: 
Page 
[[Brain Storm]]

Page properties :  alias: Ideas Hub 

So if any "Ideas Hub" writing another page,  For Brain Storm Page  unliked referance is also "Ideas Hub"

**Comment by usoonees** [comment]
Please check newest version, have a bug on retrieving alias names before.

Let me know if you still have this issue.

**Comment by Slabhub** [comment]
i checked. it works now for alias Thank you .
